[package]
name = "teal-main"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
teal-base = { path = "../teal-base" }
teal-ops = { path = "../teal-ops" }
